### ISSUE TITLE
No registered env with id: halfcheetah-medium-v2

### ISSUE THREAD

**Issue by boykac** [kzl/decision-transformer#44]
python download_d4rl_datasets.py
->
Traceback (most recent call last):
  File "download_d4rl_datasets.py", line 12, in <module>
    env = gym.make(name)
  File "/public/home/chenxn1/anaconda3/envs/decision-transformer-gym/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/public/home/chenxn1/anaconda3/envs/decision-transformer-gym/lib/python3.8/site-packages/gym/envs/registration.py", line 89, in make
    spec = self.spec(path)
  File "/public/home/chenxn1/anaconda3/envs/decision-transformer-gym/lib/python3.8/site-packages/gym/envs/registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: halfcheetah-medium-v2

**Comment by cwf1005** [comment]
You should install d4rl, and import d4rl before gym.make()

**Comment by ShuboLiu** [comment]
After I import d4rl first, this error remians. Can anyone help me with it?

**Comment by tangtaotao123** [comment]
maybe you didn't install mlrl

**Comment by arks22** [comment]
I had the same problem, but after installing D4RL using this method from the D4RL README, I was able to download the data sets such as halhcheetah-midium-v2 and others.
https://github.com/Farama-Foundation/D4RL#setup
Perhaps you should also make sure that MuJoCo2.1.0 is downloaded correctly.

Hope this helps.
