### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by LLL-YUE** [kzl/decision-transformer#77]
When I run experiment.py，the mistakes appear as follows:
NVIDIA GeForce RTX 3060 Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3060 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "/home/liuyue/projects/decision-transformer-master/gym/experiment.py", line 308, in <module>
    experiment('gym-experiment', variant=vars(args))
  File "/home/liuyue/projects/decision-transformer-master/gym/experiment.py", line 278, in experiment
    outputs = trainer.train_iteration(num_steps=variant['num_steps_per_iter'], iter_num=iter+1, print_logs=True)
  File "/home/liuyue/projects/decision-transformer-master/gym/decision_transformer/training/trainer.py", line 30, in train_iteration
    train_loss = self.train_step()
  File "/home/liuyue/projects/decision-transformer-master/gym/decision_transformer/training/seq_trainer.py", line 13, in train_step
    state_preds, action_preds, reward_preds = self.model.forward(
  File "/home/liuyue/projects/decision-transformer-master/gym/decision_transformer/models/decision_transformer.py", line 63, in forward
    state_embeddings = self.embed_state(states)
  File "/home/liuyue/anaconda3/envs/decision-transformer-gym/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/liuyue/anaconda3/envs/decision-transformer-gym/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/liuyue/anaconda3/envs/decision-transformer-gym/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by koolgax99** [comment]
Hi @LLL-YUE! Were you able to solve this issue?
